[project]
name = "label-studio-ml-backend"
version = "1.0.21"
description = "custom verison of sam2 video"
package-mode = false
authors = [
    {name = "Diego Droghini",email = "diego.droghini@xtechnologies.it"}
]
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "flask (>=2.3,<2.4)",
    "colorama (>=0.4,<0.5)",
    "requests (>=2.32.4,<2.33.0)",
    "semver (>=3.0.2,<3.1.0)",
    "label-studio-sdk @ git+https://github.com/HumanSignal/label-studio-sdk.git",
    "cuda-python (>=12.9.0,<13.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "gunicorn (==22.0.0)",
    "label-studio-ml @ git+https://github.com/HumanSignal/label-studio-ml-backend.git",
    "torch (>=2.7.1,<3.0.0)",
    "sam-2 @ git+https://github.com/facebookresearch/sam2.git",
    "huggingface-hub (>=0.34.3,<0.35.0)",
    "decord (>=0.6.0,<0.7.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
